### ISSUE TITLE
¿Qué pasa con la etiqueta de Google fonts al validarla?

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/c-s1-vleg#4]
¿Alguien sabe decir qué pasa? ¿Y cómo solucionarlo?

**Comment by mariav53** [comment]
El link descargado de Google Fonts incluye el caracter ( | ) para separar las dos tipografía y el W3 Validator lo da como error.
Hemos descargado los links de las tipografías por separado para solucionarlo.

**Comment by oneeyedman** [comment]
Excelente!

Otra opción es meterlo por css con el `@import` o [sustituir el carácter por un código equivalente](https://stackoverflow.com/questions/22466913/google-fonts-url-break-html5-validation-on-w3-org).
